---
- name: Netology ML Playbook
  hosts: netology-ml
  become: true
  vars_files:
    - group_vars/all.yaml

  tasks:

    - name: Проверка доступности хоста
      ansible.builtin.ping:

    - name: Обновление пакетов
      ansible.builtin.apt:
        update_cache: yes

    - name: Установка необходимых пакетов
      ansible.builtin.apt:
        name: "{{ packages_to_install }}"
        state: present
      
    - name: Копирование файла test.txt
      ansible.builtin.copy:
        src: test.txt
        dest: /tmp/test.txt
        mode: '0644'

    - name: Создание пользователей и их home-директорий
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"
